# Generated by Django 4.2.23 on 2025-07-29 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment_image_product_image_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTimeCreate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTimeCreate'),
        ),
    ]
