# Generated by Django 4.2.23 on 2025-07-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTimeCreate'),
        ),
    ]
