# Generated by Django 4.2.23 on 2025-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='author_user/author_cover/', verbose_name='Product Image'),
        ),
    ]
