# Generated by Django 4.2.23 on 2025-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_image_product_image_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comment/author_comment_cover/', verbose_name='Author Comment Image'),
        ),
    ]
