version: "28.0"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-_^sf*f16a==q9_m5&yt125#_c^pz!a4p6w2xl!=+b@ko9*sx5z"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:17
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
