from django.utils.translation import gettext as _

def add_variable_to_context(request):
    return {
        'homePage': _('HomePage'),
        'welcome': _('Welcome'),
        'logout': _('Log Out'),
        'login': _('Log In'),
        'signup': _('Sign Up'),
        'booksTitle': _('Books'),
        'home': _('Home'),
        'addNewBook': _('Add New Book'),
        'or': _('Or'),
        'link': _('Link'),
        'github': _('GitHub'),
        'linkedin': _('Linkedin'),
        'FotgotYourPassword': _('Fotgot Your Password'),
        'bookDream':_('Book Dream'),
        'book':_('Book'),
        'send':_('Send'),
        'passwordResetForm':_('Password Reset Form'),
        'passwordResetDone':_('Password Reset Done'),
        'emailSent':_('Email Sent!'),
        'pleaseCheckYourEmailWeHaveSentYouTheInstructions':_('Please check your email. We have sent you the instructions.'),
        'setNewPassword':_('Set New Password'),
        'setNewPasswordForm':_('Set New Password Form Reset'),
        'successful':_('Successful'),
        'passwordResetComplete':_('Password reset complete!'),
        'youCanLoginOn':_('You can login on'),
        'loginPage':_('Login Page'),
        'passwordChange':_('Password Change'),
        'change':_('Change'),
        'yourPasswordWasChange':_('Your password was change.'),
        'blog':_('Blog'),
        'pages':_('Pages'),
        'contactUs':_('Contact Us'),
        'shoppingCart':_('Shopping cart'),
        'favorites':_('Favorites'),
        'orderHistory':_('Order history'),
        'aboutUs':_('About Us'),
        'rulesAndRegulations':_('Rules and regulations'),
        'developedBy':_('Developed By'),
        'areYouSureYouWantToLogout':_('Are you sure you want to logout'),
        'areYouSure':_('Are You Sure'),
        'profile':_('Profile'),
    }